package org;

public enum UserState {
    MAIN_MENU,
    IN_MENU,
    CREATING_REMINDER,
    VIEWING_REMINDERS,
    EDITING_REMINDER,
    DELETING_REMINDER,
    MANAGING_BIRTHDAYS,
    ADDING_BIRTHDAY_CONTACT_MANUALLY,
    ADDING_BIRTHDAY_NAME,
    ADDING_BIRTHDAY_PHONE,
    ADDING_BIRTHDAY_DATE,
    DELETING_BIRTHDAY
}